### ISSUE TITLE
No longer working 

### ISSUE THREAD

**Issue by jamierc** [phautamaki/TheQuantifyingStack#2]
As of 16 January the shortcut is not working for me. See error at attached image. Has the Oura API changed? 

Error- Oura data not available yet. 

![Uploading 9C12943F-11FA-42EB-9137-40DDF25EB03D.png…]()

**Comment by phautamaki** [comment]
Did the situation change? I noticed this too but it seemed the data is not syncing to the Oura cloud at the moment for some reason (for me at least). I’m aware the V1 api is going to be deprecated soon but it should not be the case at this point yet.

**Comment by jamierc** [comment]
It worked later in the day for me, so I assumed it was just a glitch. But now it’s giving the same error message again.

**Comment by phautamaki** [comment]
It is highly likely that this is s problem of Oura, not of the shortcut. They seem to have delays in the data sync at the moment. For me, the last data found from the Oura Cloud is currently from Sunday, which was 2 days ago, even though in the app I have data for today and yesterday too. It seems not even manually starting the backup process does the trick.

**Comment by jamierc** [comment]
Think you’re right. There’s a Reddit thread talking about other syncs that it has broken   
  
  
  

      
  

  
  
>

**Comment by phautamaki** [comment]
The delays seem to be over and everything should be working again. Closing this.
